# coding: utf-8

"""
    Authenticate Platform Supply Chain API

    Through this API you can Manage products and suppliers. Access to this API is restricted to authenticated users. Before accessing this API, first authenticate via the \"Account\" API. (https://uat-account.authenticateis.com/)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: platform-support@authenticateis.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import authenticate_supply_chain
from authenticate_supply_chain.api.raw_material_logistics_api import RawMaterialLogisticsApi  # noqa: E501
from authenticate_supply_chain.rest import ApiException


class TestRawMaterialLogisticsApi(unittest.TestCase):
    """RawMaterialLogisticsApi unit test stubs"""

    def setUp(self):
        self.api = RawMaterialLogisticsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_raw_materials_raw_material_id_logistics_logistic_id_delete(self):
        """Test case for api_v1_raw_materials_raw_material_id_logistics_logistic_id_delete

        Delete a raw material logistic  # noqa: E501
        """
        pass

    def test_api_v1_raw_materials_raw_material_id_logistics_post(self):
        """Test case for api_v1_raw_materials_raw_material_id_logistics_post

        Create a new logistic for a raw material  # noqa: E501
        """
        pass

    def test_list_logistics(self):
        """Test case for list_logistics

        Returns a list of all logistics for the given raw material  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
