# coding: utf-8

"""
    Authenticate Platform Supply Chain API

    Through this API you can Manage products and suppliers. Access to this API is restricted to authenticated users. Before accessing this API, first authenticate via the \"Account\" API. (https://uat-account.authenticateis.com/)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: platform-support@authenticateis.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import authenticate_supply_chain
from authenticate_supply_chain.api.product_line_approval_request_api import ProductLineApprovalRequestApi  # noqa: E501
from authenticate_supply_chain.rest import ApiException


class TestProductLineApprovalRequestApi(unittest.TestCase):
    """ProductLineApprovalRequestApi unit test stubs"""

    def setUp(self):
        self.api = ProductLineApprovalRequestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_product_line_approval_request_post(self):
        """Test case for api_v1_product_line_approval_request_post

        Save a new approval request for a product line approval  # noqa: E501
        """
        pass

    def test_api_v1_product_line_approval_request_product_line_approval_id_get(self):
        """Test case for api_v1_product_line_approval_request_product_line_approval_id_get

        Returns a list of all approval requests for a product line approval, meeting the request criteria  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
