# coding: utf-8

"""
    Authenticate Platform Supply Chain API

    Through this API you can Manage products and suppliers. Access to this API is restricted to authenticated users. Before accessing this API, first authenticate via the \"Account\" API. (https://uat-account.authenticateis.com/)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: platform-support@authenticateis.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import authenticate_supply_chain
from authenticate_supply_chain.api.raw_material_records_api import RawMaterialRecordsApi  # noqa: E501
from authenticate_supply_chain.rest import ApiException


class TestRawMaterialRecordsApi(unittest.TestCase):
    """RawMaterialRecordsApi unit test stubs"""

    def setUp(self):
        self.api = RawMaterialRecordsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_raw_material_records_status_count_get(self):
        """Test case for api_v1_raw_material_records_status_count_get

        Returns counts of Raw material records based on the resource parameters  # noqa: E501
        """
        pass

    def test_api_v1_raw_materials_raw_material_id_records_post(self):
        """Test case for api_v1_raw_materials_raw_material_id_records_post

        Create a raw material record for a raw material  # noqa: E501
        """
        pass

    def test_api_v1_raw_materials_raw_material_id_records_raw_material_record_id_delete(self):
        """Test case for api_v1_raw_materials_raw_material_id_records_raw_material_record_id_delete

        Delete a raw material record.  # noqa: E501
        """
        pass

    def test_api_v1_raw_materials_raw_material_id_records_raw_material_record_id_get(self):
        """Test case for api_v1_raw_materials_raw_material_id_records_raw_material_record_id_get

        Returns a specified raw material record  # noqa: E501
        """
        pass

    def test_api_v1_raw_materials_raw_material_id_records_raw_material_record_id_put(self):
        """Test case for api_v1_raw_materials_raw_material_id_records_raw_material_record_id_put

        Fully update a raw material record. All elements must be supplied or fields will be updated to default values  # noqa: E501
        """
        pass

    def test_list_all_raw_material_records(self):
        """Test case for list_all_raw_material_records

        Returns a list of Raw material records for the requesting company  # noqa: E501
        """
        pass

    def test_list_raw_material_records(self):
        """Test case for list_raw_material_records

        Returns a list of Raw material records for a raw material  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
