# coding: utf-8

"""
    Authenticate Platform Supply Chain API

    Through this API you can Manage products and suppliers. Access to this API is restricted to authenticated users. Before accessing this API, first authenticate via the \"Account\" API. (https://uat-account.authenticateis.com/)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: platform-support@authenticateis.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import authenticate_supply_chain
from authenticate_supply_chain.api.company_licence_requests_api import CompanyLicenceRequestsApi  # noqa: E501
from authenticate_supply_chain.rest import ApiException


class TestCompanyLicenceRequestsApi(unittest.TestCase):
    """CompanyLicenceRequestsApi unit test stubs"""

    def setUp(self):
        self.api = CompanyLicenceRequestsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_companies_company_id_licence_requests_licence_request_id_complete_post(self):
        """Test case for api_v1_companies_company_id_licence_requests_licence_request_id_complete_post

        Sets a company licence request as completed  # noqa: E501
        """
        pass

    def test_api_v1_companies_company_id_licence_requests_licence_request_id_reject_post(self):
        """Test case for api_v1_companies_company_id_licence_requests_licence_request_id_reject_post

        Sets a company licence request as rejected and sets a reason  # noqa: E501
        """
        pass

    def test_api_v1_companies_licence_requests_get(self):
        """Test case for api_v1_companies_licence_requests_get

        Returns a list of licence requests for your company  # noqa: E501
        """
        pass

    def test_api_v1_companies_licence_requests_licence_request_id_get(self):
        """Test case for api_v1_companies_licence_requests_licence_request_id_get

        Returns a licence request assigned to your company  # noqa: E501
        """
        pass

    def test_create_company_licence_request(self):
        """Test case for create_company_licence_request

        Create a company licence request  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
