# coding: utf-8

"""
    Authenticate Platform Supply Chain API

    Through this API you can Manage products and suppliers. Access to this API is restricted to authenticated users. Before accessing this API, first authenticate via the \"Account\" API. (https://uat-account.authenticateis.com/)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: platform-support@authenticateis.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import authenticate_supply_chain
from authenticate_supply_chain.api.declared_supply_chain_status_api import DeclaredSupplyChainStatusApi  # noqa: E501
from authenticate_supply_chain.rest import ApiException


class TestDeclaredSupplyChainStatusApi(unittest.TestCase):
    """DeclaredSupplyChainStatusApi unit test stubs"""

    def setUp(self):
        self.api = DeclaredSupplyChainStatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_declared_supply_chain_declared_supply_chain_id_declared_supply_chain_status_get(self):
        """Test case for api_v1_declared_supply_chain_declared_supply_chain_id_declared_supply_chain_status_get

        Returns a list of all declared supply chains statuses by declared supply chain id.  # noqa: E501
        """
        pass

    def test_api_v1_declared_supply_chain_declared_supply_chain_id_declared_supply_chain_status_post(self):
        """Test case for api_v1_declared_supply_chain_declared_supply_chain_id_declared_supply_chain_status_post

        Create a new Declared Supply Chain Status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
