# coding: utf-8

"""
    Authenticate Platform Supply Chain API

    Through this API you can Manage products and suppliers. Access to this API is restricted to authenticated users. Before accessing this API, first authenticate via the \"Account\" API. (https://uat-account.authenticateis.com/)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: platform-support@authenticateis.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import authenticate_supply_chain
from authenticate_supply_chain.api.ons_company_types_api import OnsCompanyTypesApi  # noqa: E501
from authenticate_supply_chain.rest import ApiException


class TestOnsCompanyTypesApi(unittest.TestCase):
    """OnsCompanyTypesApi unit test stubs"""

    def setUp(self):
        self.api = OnsCompanyTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_company_type(self):
        """Test case for get_company_type

        Returns a specified ONS company type  # noqa: E501
        """
        pass

    def test_get_company_types(self):
        """Test case for get_company_types

        Returns a list of all ONS company types meeting the request criteria  # noqa: E501
        """
        pass

    def test_get_company_types_for_sector(self):
        """Test case for get_company_types_for_sector

        Returns a list of all ONS company types meeting the request criteria for a give ONS sector  # noqa: E501
        """
        pass

    def test_get_ons_sectors(self):
        """Test case for get_ons_sectors

        Returns a list of all ONS business sectors meeting the request criteria  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
