# coding: utf-8

"""
    Authenticate Platform Supply Chain API

    Through this API you can Manage products and suppliers. Access to this API is restricted to authenticated users. Before accessing this API, first authenticate via the \"Account\" API. (https://uat-account.authenticateis.com/)  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: platform-support@authenticateis.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import authenticate_supply_chain
from authenticate_supply_chain.api.site_relationship_api import SiteRelationshipApi  # noqa: E501
from authenticate_supply_chain.rest import ApiException


class TestSiteRelationshipApi(unittest.TestCase):
    """SiteRelationshipApi unit test stubs"""

    def setUp(self):
        self.api = SiteRelationshipApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_site_relationship_site_id_patch(self):
        """Test case for api_v1_site_relationship_site_id_patch

        Partially update a site relationship. Only provided fields will be updated  # noqa: E501
        """
        pass

    def test_api_v1_site_relationship_site_id_post(self):
        """Test case for api_v1_site_relationship_site_id_post

        Create a new site relationship  # noqa: E501
        """
        pass

    def test_api_v1_site_relationship_site_id_put(self):
        """Test case for api_v1_site_relationship_site_id_put

        Update an existing site relationship  # noqa: E501
        """
        pass

    def test_get_all_site_relationship_values(self):
        """Test case for get_all_site_relationship_values

        Returns a specified site relationship's values based on viewing company  # noqa: E501
        """
        pass

    def test_get_site_relationship(self):
        """Test case for get_site_relationship

        Returns a specified site relationship based on viewing company  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
